version: '3.9'
services:
  postgres:
    image: postgres:14
    restart: always
    networks:
      - backend
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    networks:
     - backend
    ports:
      - 80:80
    depends_on:
     - postgres
    env_file:
      - .env

volumes:
  db_data:

networks:
  backend:
    external: true
    name: net_secured
